### ISSUE TITLE
How configure V2ray-plugin in andriod

### ISSUE THREAD

**Issue by onlyJinx** [shadowsocks/v2ray-plugin-android#11]
I use ss-libev+websocket+tls+nginx;
My website is configured with a SSL certificate and working.I can't connect to the server in andriod,How should I configure, this is my profile:
nginx:

    # HTTPS server
    #
    server {
        listen       443 ssl;
        server_name  iruohui.tpp;

        ssl_certificate      /etc/www/key/server.crt;        ssl_certificate_key  /etc/www/key/server.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root   html;
            index  index.html index.htm;
        }
        location /ray/ {
            proxy_pass   http://127.0.0.1:100/;

        }
    }

config.json:
###
{
    "server":"0.0.0.0",
    "server_port":100,
    "local_port":1080,
    "password":"#######",
    "timeout":60,
    "method":"xchacha20-ietf-poly1305",
    "fast_open": true,
    "plugin":"/v2ray-plugin",
    "plugin_opts":"server;tls;cert=/etc/www/key/server.crt;key=/etc/www/key/server.key;host=www.iruohui.top;loglevel=none",
    "nameserver": "8.8.8.8",
    "mode": "tcp_and_udp"

}

ss-server INFO:
###
Sep 27 01:00:18 instance-1 ss-server[22817]: 2019-09-27 01:00:18 INFO: UDP relay enabled
Sep 27 01:00:18 instance-1 ss-server[22817]: 2019-09-27 01:00:18 INFO: initializing ciphers... xchacha20-ietf-poly1305
Sep 27 01:00:18 instance-1 ss-server[22817]: 2019-09-27 01:00:18 INFO: using nameserver: 8.8.8.8
Sep 27 01:00:18 instance-1 ss-server[22817]: 2019-09-27 01:00:18 INFO: tcp server listening at 127.0.0.1:39897
Sep 27 01:00:18 instance-1 ss-server[22817]: 2019-09-27 01:00:18 INFO: udp server listening at 0.0.0.0:100Sep 27 01:00:18 instance-1 ss-server[22817]: 2019-09-27 01:00:18 INFO: running from root user
Sep 27 01:00:18 instance-1 ss-server[22817]: 2019/09/27 01:00:18 V2Ray 4.16 (Po) Custom
Sep 27 01:00:18 instance-1 ss-server[22817]: 2019/09/27 01:00:18 A unified platform for anti-censorship.
Sep 27 01:16:59 instance-1 ss-server[22817]: 2019/09/27 01:16:59 http: TLS handshake error from 193.112.48.179:59070: EOF
Sep 27 01:28:15 instance-1 ss-server[22817]: 2019/09/27 01:28:15 http: TLS handshake error from 127.0.0.1:59242: tls: first record does not look like a TLS handshake

![Screenshot_20190927-093008_Firefox](https://user-images.githubusercontent.com/21324835/65735323-7c6d3d80-e109-11e9-915c-b6e552d0addb.jpg)

![Screenshot_20190927-094340_Shadowsocks](https://user-images.githubusercontent.com/21324835/65735829-66f91300-e10b-11e9-99cc-3cd38cbb7950.jpg)

**Comment by seclog** [comment]
have you solve your problem? I have no problem when I used windows shadowsocks client with v2ray-plugin, but Android with v2ray-plugin  has not been successful.

**Comment by onlyJinx** [comment]
> have you solve your problem? I have no problem when I used windows shadowsocks client with v2ray-plugin, but Android with v2ray-plugin has not been successful.

I can't solve the problem,I will try it on the computer tomorrow.

**Comment by darkflame0** [comment]
> have you solve your problem? I have no problem when I used windows shadowsocks client with v2ray-plugin, but Android with v2ray-plugin has not been successful.

I have same issue...

**Comment by huang-ju** [comment]
@onlyJinx 解决了吗？我不知道怎样配置文件

**Comment by pikadun** [comment]
@onlyJinx  买别人的v2ray账号可以用吗

**Comment by onlyJinx** [comment]
> @onlyJinx 买别人的v2ray账号可以用吗

不知道，我用vps自己搭建的

**Comment by onlyJinx** [comment]
> @onlyJinx 解决了吗？我不知道怎样配置文件

没有，算了，不折腾了
