### ISSUE TITLE
Completely disable multiplexing (aka mux=0)

### ISSUE THREAD

**Issue by joshua-kfbb** [shadowsocks/v2ray-plugin-android#15]
The upsteam v2ray-plugin has supported completely disabling mux. https://github.com/shadowsocks/v2ray-plugin/pull/123  Will this android plugin merge this feature?

**Comment by enihcam** [comment]
https://github.com/shadowsocks/v2ray-plugin-android/blob/master/app/src/main/java/com/github/shadowsocks/plugin/v2ray/ConfigFragment.kt#L104

I'm guessing this line is the one to be fixed.

**Comment by Mygod** [comment]
What makes you think that this feature is not merged?
