### ISSUE TITLE
Change plugin id from 'v2ray' to 'v2ray-plugin' for consistency

### ISSUE THREAD

**Issue by ghost** [shadowsocks/v2ray-plugin-android#18]
#13 was closed without any comments so I opened another one.

**Comment by Mygod** [comment]
Maybe but this would introduce problems with existing profiles.

**Comment by CzBiX** [comment]
@Mygod How about add a feature to support plugin alias, or just convert it when read profiles field.

**Comment by Mygod** [comment]
@CzBiX Good idea. We can support an `IS_ALIAS` metadata.

**Comment by CzBiX** [comment]
When user import profile from QRcode that generated on other platform, or when SIP008 becomes popular, this issue will be big problem.
