### ISSUE TITLE
mux=0 报错：libss-local exits too fast 

### ISSUE THREAD

**Issue by xtremforce** [shadowsocks/v2ray-plugin-android#20]
由于服务器上设置了 mux=0 
但在 Android 的插件里一旦将 Concurrent connections 设置为 0 之后，一连接就报错：
libss-local exits too fast (exit code:255)

**Comment by enihcam** [comment]
please add option for disabling mux (e.g. mux=0)

**Comment by Mygod** [comment]
Cannot reproduce.

**Comment by enihcam** [comment]
@Mygod  this is weird, did you add mux=0 on the both side? i believe multiple people are seeing this issue, because i installed the latest beta version published in the market, and it repros constantly. please let me know the magic version where this scenario works.

**Comment by kzw200015** [comment]
我遇到了同样的问题，MIUI11 Android 10 使用v2ray-plugin 1.3.0 shadowsocks 5.0.5
