### ISSUE TITLE
log file of v2ray-plugin-android

### ISSUE THREAD

**Issue by liyuqihxc** [shadowsocks/v2ray-plugin-android#23]
I am using ss-android 4.8.7 with v2ray plugin 1.3.0 from play store, and I can’t get it to connect to my ss server, but ss-windows on my pc works fine. so I change the loglevel of v2ray-plugin-android to debug hoping to find some infomation. but where is the log file stored?

**Comment by ODtian** [comment]
同问，android q连不上，pc是可以的

**Comment by Mygod** [comment]
logcat

**Comment by amirhs712** [comment]
I wish we could see the logs in the app

Could help a lot with debugging


------------

EDIT:

It turns out you could use adb for viewing logcat, I got the logs using ```adb logcat | findstr v2ray```
