### ISSUE TITLE
Incorrect Help Information In Plugin

### ISSUE THREAD

**Issue by changyp6** [shadowsocks/v2ray-plugin-android#4]
When entering options for "v2ray-plugin", click on the left-down connor "?" sign, there will be help information.
```
mode=string
   Transport mode: ws/quic. (default "ws")
```
However, if you enter `mode=ws`, the plugin won't work, you need to enter `mode=websocket`

Please change this Incorrect information.

**Comment by Mygod** [comment]
Already fixed.
