### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [shadowsocks/v2ray-plugin-android#5]
Would be nice to add this plugin to the F-Droid repository. Don't you mind?

**Comment by Mygod** [comment]
Contributions are welcome.

**Comment by moralrebuild** [comment]
Good suggestion.

**Comment by mahc9kez** [comment]
#17

**Comment by mahc9kez** [comment]
V2ray Plugin have been successfully built on F-Droid, please install and check if it works properly (I have tried and it works for me). F-Droid will automatically check new tags, build for each new `^v` tags.
https://f-droid.org/en/packages/com.github.shadowsocks.plugin.v2ray/

@Mygod @madeye May you add [F-Droid Badge](https://gitlab.com/fdroid/artwork/tree/master/badge) to README? and [trust](https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/java/com/github/shadowsocks/plugin/PluginManager.kt#L63) F-Droid's signature in shadowsocks-android? To get the public key, just download [the apk](https://f-droid.org/repo/com.github.shadowsocks.plugin.v2ray_1030000.apk), and then
`keytool -printcert -jarfile ./com.github.shadowsocks.plugin.v2ray_1030000.apk -rfc`
or
`unzip -p ./com.github.shadowsocks.plugin.v2ray_1030000.apk META-INF/EABA26EE.RSA | keytool -printcert -rfc`

Note F-Droid generate new key for each new app by default, so this key is dedicated to V2ray Plugin on F-Droid. If other shadowsocks-android plugin was added to F-Droid in the future, you may ask F-Droid maintainer to sign it with the same key or trust each key for each plugin on F-Droid.

**Comment by Mygod** [comment]
I think it is better to sign different plugins with different signature.
