### ISSUE TITLE
android 9 连不上呀？

### ISSUE THREAD

**Issue by ilaziness** [shadowsocks/v2ray-plugin-android#9]
shadowsocks 版本是4.7.3，V2ray-Plugin 版本是1.2
Android版本是9.
插件参数：`mode=quic;host=xx.xxxx.net`，客户端和服务器都不加插件就没问题。
同一个WiFi下面，桌面版是没问题的。
手机版就是连不上，怎么回事？服务器日志调到`loglevel=info`也没有连接上的日志。
没有任何报错信息。

**Comment by Mygod** [comment]
Cannot reproduce.

**Comment by C7AB** [comment]
俺也一样
去掉插件可以，带插件安卓不行PC可以
